// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function Move(arg1, arg2) {
  return window['go']['main']['App']['Move'](arg1, arg2);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}
