// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hide():Promise<void>;

export function Move(arg1:number,arg2:number):Promise<void>;

export function Show():Promise<void>;
